"""empty message

Revision ID: 69762a4f9954
Revises: 4ef9f7331ee3
Create Date: 2022-05-11 18:55:49.097138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69762a4f9954'
down_revision = '4ef9f7331ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('char_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('vehicles_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_4', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_3', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_1', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'vehicles', ['vehicles_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'people', ['char_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'planets', ['planets_id'], ['id'])
    op.drop_column('favorites', 'favourite_user')
    op.drop_column('favorites', 'favourite_planets')
    op.drop_column('favorites', 'favourite_char')
    op.drop_column('favorites', 'favourite_vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favourite_vehicles', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('favourite_char', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('favourite_planets', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('favourite_user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_1', 'favorites', 'people', ['favourite_char'], ['id'])
    op.create_foreign_key('favorites_ibfk_3', 'favorites', 'user', ['favourite_user'], ['id'])
    op.create_foreign_key('favorites_ibfk_4', 'favorites', 'vehicles', ['favourite_vehicles'], ['id'])
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'planets', ['favourite_planets'], ['id'])
    op.drop_column('favorites', 'vehicles_id')
    op.drop_column('favorites', 'planets_id')
    op.drop_column('favorites', 'char_id')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
